# Generated by Django 3.0.3 on 2020-03-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='podcast',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musica.Genre'),
        ),
        migrations.AlterModelTable(
            name='list',
            table='List',
        ),
    ]
