# Generated by Django 3.0.3 on 2020-04-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
