# Generated by Django 3.0.3 on 2020-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lists',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, to='musica.Playlist'),
        ),
    ]
