# Generated by Django 3.0.3 on 2020-03-22 19:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('musica', '0002_auto_20200322_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='S7_user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('segundos', models.IntegerField(null=True)),
                ('favorito', models.ManyToManyField(related_name='favorito', to='musica.Audio')),
                ('podcasts', models.ManyToManyField(to='musica.Podcast')),
                ('reproduciendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musica.Audio')),
                ('siguiendo', models.ManyToManyField(related_name='seguidor', to='musica.S7_user')),
            ],
            options={
                'db_table': 'S7_user',
                'managed': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.S7_user'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
