# Generated by Django 3.0.3 on 2020-04-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_auto_20200406_1509'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='album',
        #     name='number_songs',
        # ),
        # migrations.RemoveField(
        #     model_name='artist',
        #     name='number_albums',
        # ),
        # migrations.RemoveField(
        #     model_name='artist',
        #     name='number_songs',
        # ),
        # migrations.RemoveField(
        #     model_name='playlist',
        #     name='duration',
        # ),
    ]
