# Generated by Django 3.0.3 on 2020-04-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_auto_20200402_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='number_songs',
            field=models.IntegerField(default=0),
        ),
    ]
