# Generated by Django 3.0.3 on 2020-04-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_auto_20200407_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='URI',
            field=models.URLField(),
        ),
    ]
