# Generated by Django 3.0.3 on 2020-04-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_auto_20200326_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('icon', models.FileField(blank=True, upload_to='')),
                ('duration', models.IntegerField(default=0)),
                ('folders', models.ManyToManyField(to='musica.Folder')),
            ],
            options={
                'db_table': 'List',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='lists',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='musica.Playlist'),
        ),
    ]
