# Generated by Django 3.0.3 on 2020-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_auto_20200413_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='id_listenotes',
            field=models.IntegerField(default=0),
        ),
    ]
