# Generated by Django 3.0.3 on 2020-04-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_auto_20200402_1337'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='Playlist',
        ),
    ]
