# Generated by Django 3.0.3 on 2020-04-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_genre_id_listenotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='canal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='podcast',
            name='id_listenotes',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='id_listenotes',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='RSS',
            field=models.URLField(),
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='genre',
        ),
        migrations.AddField(
            model_name='podcast',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='podcasts', to='musica.Genre'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
