# Generated by Django 3.0.3 on 2020-04-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0009_auto_20200414_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Channel',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='image',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='musica.Podcast'),
        ),
    ]
