# Generated by Django 3.0.3 on 2020-04-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0010_auto_20200414_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='canal',
        ),
        migrations.AddField(
            model_name='podcast',
            name='channel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='musica.Channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
