# Generated by Django 3.0.3 on 2020-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0011_auto_20200414_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
