# Generated by Django 3.0.3 on 2020-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0012_auto_20200414_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s7_user',
            name='favorito',
            field=models.ManyToManyField(blank=True, related_name='user', to='musica.Audio'),
        ),
    ]
