# Generated by Django 3.0.3 on 2020-04-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0013_auto_20200415_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s7_user',
            name='favorito',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='musica.Song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='musica.S7_user'),
        ),
    ]
