# Generated by Django 3.0.3 on 2020-04-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0014_auto_20200415_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='s7_user',
            name='favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fav_user', to='musica.Playlist'),
        ),
    ]
