# Generated by Django 3.0.6 on 2020-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0016_song_times_faved'),
    ]

    operations = [
        migrations.AddField(
            model_name='s7_user',
            name='icon',
            field=models.FileField(default='../static/default-user-pic.png', upload_to=''),
        ),
    ]
